### ISSUE TITLE
How can i build ```total_word_feature_extractor.dat``` word  representation with my own business data？

### ISSUE THREAD

**Issue by terryKing1992** [zqhZY/rasa_chatbot#2]
is there any guide post about using MITIE tools to train my own train data to MITIE model？
thanks a lot

**Comment by zqhZY** [comment]
Thanks for this issue!.  You can train your own MITIE model using following method:
```
$ git clone https://github.com/mit-nlp/MITIE.git
$ cd MITIE/tools/wordrep
$ mkdir build
$ cd build
$ cmake ..
$ cmake --build . --config Release
$ ./wordrep -e /path/to/your/folder_of_cutted_text_files
``` 
/path/to/your/folder_of_cutted_text_files above is a directory path in which has word cutted  data files to train. This process may cost one or two days.

I will add this instruction to README.md later.

**Comment by terryKing1992** [comment]
thanks for your reply.
